Sprint2/step2
AlexTolevich/react-burger pull request #2
Opened 2023-01-23 17:55 UTC by AlexTolevich

2023-01-23 19:26 UTC, andryxxa93 requested changes
Отличная работа! `Redux` и `DnD` настроены и работают правильно.
Что понравилось:
- Реализована навигация по категориям.
- Правильно организовано хранилище.
- Редьюсеры - чистые функции.

Есть только одно небольшое замечание:
 - Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

Удачных правок!

2023-01-23 19:26 UTC, andryxxa93 commented on src/components/BurgerConstructor/BurgerConstructor.js
> +  const burger = useSelector(state => state.burgerConstructor.burger);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-01-24 11:00 UTC, AlexTolevich commented on src/components/BurgerConstructor/BurgerConstructor.js
> +  const burger = useSelector(state => state.burgerConstructor.burger);
Добавил папку selectors/ и вынес в нее колбэк функции для передачи в useSelector

2023-01-24 11:00 UTC, AlexTolevich commented
Добавил обнуление номера заказа при ошибке, а так же возврат в исходное состояние state.order при закрытии модального окна. Добавил удаление списка ингредиентов бургера при успешном POST запросе.  Добавил работу прелоадера при запросах к API сервера.

2023-01-24 20:22 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!

2023-01-25 05:23 UTC, merged